spring:
  datasource:
    url: jdbc:h2:mem:lab1db
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console.enabled: true       # ← чтобы заглянуть в БД
  jpa:
    hibernate:
      ddl-auto: update          # ← авто‑создавать и обновлять таблицы
    show-sql: true
